title:        Pietro
tagline:      'Passarelli'
name:         'Tips Tricks & Quick Fix'
description:  "Tips Tricks & Quick Fix by <a href='https://twitter.com/pietropassarell' target='_blank'>@pietropassarell</a>i."
url:          https://pietropassarelli.com
#https://pietropassarelli.com
#url: https://localhost:4000
version:      1.1.1
author:
  name:       'Pietro'
  email:      'pietro.passarelli@gmail.com'
# highlighter:  pygments
# markdown: redcarpet
# redcarpet:
#   extensions: [“no_intra_emphasis”, “fenced_code_blocks”, “autolink”, “strikethrough”, “superscript”]
permalink:    pretty

# paginate:     5

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
# redcarpet:
#     extensions: [
#         'no_intra_emphasis',
#         'fenced_code_blocks',
#         'autolink',
#         'strikethrough',
#         'superscript',
#         'with_toc_data',
#         'tables',
#         'hardwrap'
#     ]

# Owner/author information
owner:
  name:           Pietro
  last_name:      Passarelli
  # avatar:         bio-photo.jpg
  bio:            "Developer/film-maker."# Working in the intersection between factual/documentary production and software development."
  # extended_bio:   "Developer/film-maker. Working in the intersection between factual/documentary production and software development."
  email:          pietro.passarelli@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        pietropassarell
  facebook:       pietro.passarelli
  github:         pietrop
  linkedin:       pietropassarelli
  # flickr:         jasz
  # vimeo:          pietropassarelli
  # talent_manager: "6010/pietro-passarelli" # or just 6010 visit your profile URL to find out the number.
  # tumblr:
  # lastfm:
  # youtube:        jaszjasm
  # skype:         "jasszz"
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:   "+PietroPassarelli" #works with custum url
  # phone:         "00447936180742"   #needs to be put between ""
  #about image in about page /img/
  about:          ubiq/pietro.jpeg
  videocolor:     theme-base-0f

categories: [video, tech, photos, articles]


# https://github.com/mdo/hyde


manifest_name: Pietro Passarelli
manifest_short_name: Pietro P # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: en
manifest_background_color: white
manifest_short_name:
manifest_display: standalone