title:        TTQF
tagline:      'Tips Tricks & Quick Fix - dev'
name:         'Tips Tricks & Quick Fix'
description:  "Tips Tricks & Quick Fix by <a href='http://twitter.com/pietropassarell' target='_blank'>@pietropassarell</a>i."
url:          http://127.0.0.1:4000
version:      1.1.1
author:
  name:       'Pietro'
  email:      'pietro.passarelli@gmail.com'
markdown: redcarpet
redcarpet:
  extensions: [“no_intra_emphasis”, “fenced_code_blocks”, “autolink”, “strikethrough”, “superscript”]
permalink:    pretty
highlighter:  pygments

# Owner/author information
owner:
  name:           Pietro
  last_name:      Passarelli
  # avatar:         bio-photo.jpg
  bio:            "Developer/film-maker."# Working in the intersection between factual/documentary production and software development."
  # extended_bio:   "Developer/film-maker. Working in the intersection between factual/documentary production and software development."
  email:          pietro.passarelli@gmail.com
  twitter:        pietropassarell
  facebook:       pietro.passarelli
  github:         pietrop
  linkedin:       pietropassarelli
  about:          ubiq/pietro.jpeg
  videocolor:     theme-base-0f

categories: [video, tech, photos, articles, blog]


# to be able to use url for production and development without need to change them for build.
#$ jekyll build --config _config.yml,_config_dev.yml --watch
