name: Deploy branch preview

on:
  push:
    branches-ignore:
      - master
      - gh-pages

jobs:
  preview:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build:preview
        env:
          PATH_PREFIX: /preview/${{ github.ref_name }}

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: preview/${{ github.ref_name }}
          keep_files: true
